### ISSUE TITLE
Hooks are called two times

### ISSUE THREAD

**Issue by rflipo-dev** [doublemarked/loopback-component-model-fragments#1]
it goes through hooks two times for a single call :

```
Model.observe('before save', (ctx, next) => {
    console.log('it logs two times');
    next();
  });
```

**Comment by doublemarked** [comment]
Hello Rémi!

I am unfortunately unable to reproduce this problem. Can you please share with me more information about your setup?

**Comment by rflipo-dev** [comment]
Here it is : (just writing what could possibly do it)

```
"loopback": "^2.22.0",
"loopback-boot": "^2.6.5",
"babel-cli": "^6.11.4",
"babel-preset-es2015": "^6.9.0"
```

Node 6.2.2

**Comment by rflipo-dev** [comment]
as said in this post : https://github.com/strongloop/loopback/issues/2457
loopback duplicates my models, for example i'll have a model 'form' and a model 'Form'...

**Comment by doublemarked** [comment]
What you've pasted above is from package.json but may not reflect the actual module versions. Can you do an `npm ls`? But regardless, please ensure `loopback-boot` is up to date and then retry. For example, my `loopback-boot` is at 2.21.0.

That said - probably indeed I should fix this as it's easy to fix in a way that will work with prior versions. But let's first ascertain whether that is the cause or not.

**Comment by doublemarked** [comment]
Sorry, I focused on loopback-boot, but it is something from the main loopback. FWIW I'm at `loopback` version 2.29.1

**Comment by doublemarked** [comment]
I've pushed a new version (0.1.2) which changes how it loops over the models. Can you please give it a try?
